source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'CFProgressHUD_Example' do
  pod 'CFProgressHUD', :path => '../'

  target 'CFProgressHUD_Tests' do
    inherit! :search_paths

    
  end
end
